move build, ignore commit errors

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -35,8 +35,6 @@ jobs:
         run: |-
           nix profile install .#updateLocks
           nix run .#updateLocks
-      - name: Build example
-        run: nix profile install .#example
       - if: matrix.os == 'ubuntu-22.04'
         name: Update README
         run: |-
@@ -50,8 +48,11 @@ jobs:
           git add .
           git commit \
             -m "action: Update flake locks" \
-            -m "action: Update README"
+            -m "action: Update README" \
+            || echo "commit failed!"
           git push
+      - name: Build example
+        run: nix profile install .#example
     strategy:
       matrix:
         os:
